### ISSUE TITLE
limits above 1000 should be supported

### ISSUE THREAD

**Issue by jclulow** [joyent/node-lomstream#3]
There doesn't seem to be a particularly good reason to constrain the limit to `1000`, but when I pass in a limit of, say, `1024`, I get this assertion:

```
mls: AssertionError: limit must be in the range [ 1, 1000 ]
    at Object.module.exports.(anonymous function) [as ok] (/Users/jclulow/proj/node-manta/node_modules/assert-plus/assert.js:242:35)
    at new LOMStream (/Users/jclulow/proj/node-manta/node_modules/lomstream/lib/lomstream.js:193:13)
    at MantaClient.createListStream (/Users/jclulow/proj/node-manta/lib/client.js:1241:15)
...
```

**Comment by rmustacc** [comment]
Sure, I guess it doesn't need to be overly restrictive here and we're probably better of just limiting the lower bound. And maybe making the upper bound be UINT32_MAX or something.

**Comment by jclulow** [comment]
Or even `INT32_MAX`, given Javascript and numbers.
